### ISSUE TITLE
Negative Z axis in normals image

### ISSUE THREAD

**Issue by lefreud** [ViLab-UCSD/OpenRooms#12]
Hi,

I am trying to understand why, after loading images like this:

```
raw_normals = cv2.imread(normals_path)[:, :, ::-1]
normals = raw_normals.astype(np.float32) / 127.5 - 1
normals = normals / np.maximum(
    np.sqrt(np.sum(normals * normals, axis=2, keepdims=True)),
    1e-6
)
```
The normals' z coordinate (in camera view) is sometimes positive, which shouldn't happen. Here's an example, the orange part of the couch has RGB value of around (249, 148, 97). The blue channel of 97 means a z value of -0.239 (negative doesn't make sense).

![image](https://github.com/ViLab-UCSD/OpenRooms/assets/35122940/f02d5aae-2122-43e8-a473-d3b3bead85f8) (mainxml/scene0002_00/imnormal_28.png)
Is the calculation for the `z` axis correctly done? I'm wondering if it might be due to a different calaculation at render time (e.g. different z scale or rotated normal map).

For context, here's the slide I found explaining the `normals` part of the dataset:
![image](https://github.com/ViLab-UCSD/OpenRooms/assets/35122940/a1f8edbc-790e-4128-9048-3f48cba683b9)

Thank you!

**Comment by Jerrypiglet** [comment]
Hi there, reply from Zhengqin: 

That's an interesting observation. Instead of checking if z value is smaller than 0, we should see if the cosine angle between the ray of that pixel and normal direction is smaller than 0. Please take a look at the rendering code here: [https://github.com/lzqsd/OptixRenderer/blob/3eafda5b4f47c7e44be7fc58cde215a8c1c2bc1a/src/optixRenderer/src/material/normal.cu#L66](https://urldefense.com/v3/__https://github.com/lzqsd/OptixRenderer/blob/3eafda5b4f47c7e44be7fc58cde215a8c1c2bc1a/src/optixRenderer/src/material/normal.cu*L66__;Iw!!Mih3wA!Ei5dkrVm1oU3OVq2wOO2ppIdEfFQUzvapk7s1-2hS4A32_uNUC3ccrvV3kK9VqeMDHcEFZs$)

negative z value does not necessarily mean the normal direction is not correct.

**Comment by lefreud** [comment]
Perfect, I understand, thank you!
